fix(archlinux/manjaro/frugalware): patch integrity checking
in reply to our first comment there:
https://aur.archlinux.org/packages/peerio-client/

diff --git a/pkg/archlinux/PKGBUILD b/pkg/archlinux/PKGBUILD
--- a/pkg/archlinux/PKGBUILD
+++ b/pkg/archlinux/PKGBUILD
@@ -15,8 +15,13 @@ md5sums=('8d1a2fd3630613470cff0001e7fbf427')
 build() {
     cd "${srcdir}/${pkgname}"
     curl http://linux.peerio.com/sources/07-build.patch >build.patch
-    patch -p0 <build.patch && rm -f build.patch
-    make client
+    if echo "cf041f3e07ae83a6965ccabed660f860  build.patch" | md5sum --check - --strict --quiet; then
+	patch -p0 <build.patch && rm -f build.patch
+	make client
+    else
+	echo "ERROR: patch's md5 sum differs from expected value" >&2
+	exit 1
+    fi
 }
 package() {
     cd "${srcdir}/${pkgname}"
diff --git a/pkg/frugalware/FrugalBuild b/pkg/frugalware/FrugalBuild
--- a/pkg/frugalware/FrugalBuild
+++ b/pkg/frugalware/FrugalBuild
@@ -16,8 +16,13 @@ sha1sums=('68283570e726d7011cec4520fcccd552bff1136e')
 build() {
     cd peerio-client || return 1
     curl http://linux.peerio.com/sources/07-build.patch >build.patch
-    patch -p0 <build.patch && rm -f build.patch
-    make install PREFIX=$Fdestdir/usr/share BINPREFIX=$Fdestdir/usr || Fdie
+    if echo "cf041f3e07ae83a6965ccabed660f860  build.patch" | md5sum --check - --strict --quiet; then
+	patch -p0 <build.patch && rm -f build.patch
+	make install PREFIX=$Fdestdir/usr/share BINPREFIX=$Fdestdir/usr || Fdie
+    else
+	echo "ERROR: patch's md5 sum differs from expected value" >&2
+	Fdie
+    fi
 }
 
 # optimization OK
